### PR TITLE
Fix deadlock when reserving an already allocated invoke context

### PR DESCRIPTION
**Pull request by zachbadgett**
*Issue #, if available:*

*Description of changes:* Server locks up when attempting to send multiple invocations due to a mutex's lock not being released. The fix: moved `Unlock` to defer, moved invoke context allocation to own method to avoid the lock retaining during `waitInit`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by zachbadgett** [comment]
This pull request fixes the mentioned issue while still retaining the original logic, however, the way the application uses locks and channels really need to be refactored.

**Review by calavera — APPROVED** [review]
I've applied this patch to my own fork, and it fixes the lock 👍 

@jfuss can we get this merged into main?

**Comment by jfuss** [comment]
Hey all,

First off: Thank you @zachbadgett for taking the time to send a patch. Unfortunately, we cannot accept contributions to the `lambda/*` files/packages (or whatever Go actually calls it). These files are from the actually Lambda Runtime API and we pull these to be added into this repo and shipped as RIE. At the moment, we do not have a great way to pull changes back in and (for now) have elected to not take contributions to these. 

In discussing with their team, we believe we have fixed this already internally and we are planning to do update here with updates from the actually Lambda Runtime API. If the issue isn't resolved, I am happy to find a way to get this patched here and keep things in sync so we aren't deviating from our upstream (which will cause overhead in releasing that we are trying to minimize). 

I will leave this open for now, until we get the patch out and verified.

**Comment by mgrandis** [comment]
Converting to draft to be sure we don't accidentally merge this one.

**Comment by doransmestad** [comment]
@jfuss  any estimate for a fix here?  I just ran into this problem as well. I'm happy to help out where I can (pull request, testing, etc) if that would be useful?  Thanks

**Comment by bodelsc** [comment]
Thank you [zachbadgett](https://github.com/zachbadgett) for reporting the issue and working upon a pull request.

This issue was fixed internally and when this repository was synced with the internal repository the issue was resolved so I am closing the pull request.

https://github.com/aws/aws-lambda-runtime-interface-emulator/blob/2ca3e4aec8ef5cec6139c531f8dd8c31dffc5bcd/lambda/rapidcore/server.go#L161

**Pull request closed without merging**
